name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Create the output directory
      - name: Create output directory
        run: mkdir -p dist

      # Generate the snake SVG
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Resad-d
          outputs: |
            github-snake.svg

      # List the generated file for debugging purposes
      - name: List generated files
        run: ls -la dist

      # Push the generated file to the 'output' branch
      - name: Push changes to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
